cc = gcc
all: posix_ipc-server posix_ipc-client
posix_ipc-client: posix_ipc-client.c
	cc posix_ipc-client.c -o posix_ipc-client

posix_ipc-server: posix_ipc-server.c
	cc posix_ipc-server.c -o posix_ipc-server